version: '3.7'
services:
  nginx:
    image: "nginx:alpine"
    ports:
    - "8080:8080"
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    links:
    - frontend
    - bff
  frontend:
    build:
      context: "frontend/web"
      dockerfile: "Dockerfile"
      # target: develop
    ports:
    - "8000:8000"
    # volumes:
    # - ./frontend/web:/app
    links:
    - bff
    environment:
    - API_URL_BFF=http://bff:4000
    - API_URL_BFF_RUNTIME=
  bff:
    build:
      context: backend
      dockerfile: "Dockerfile.node"
    ports:
    - "4000:4000"
    links:
    - greeter_server
    environment:
    - API_URL_GREETER=greeter_server:50051
  greeter_server:
    build:
      context: backend
      dockerfile: "Dockerfile.go"
      args:
        SERVICE_NAME: "greeter_server"
    ports:
    - "50051:50051"
    links:
    - redis
  redis:
    image: "redis:alpine"
