version: '3'
services:
  frontend:
    build:
      context: "frontend/web"
      dockerfile: "Dockerfile"
    ports:
    - "8000:8000"
    links:
    - bff
  bff:
    build:
      context: backend
      dockerfile: "Dockerfile.node"
    ports:
    - "4000:4000"
    links:
    - greeter_server
  greeter_server:
    build:
      context: backend
      dockerfile: "Dockerfile.go"
      args:
        SERVICE_NAME: "greeter_server"
    ports:
    - "50051:50051"
    links:
    - redis
  redis:
    image: "redis:alpine"
