version: '3.7'
services:
  nginx:
    image: "nginx:alpine"
    ports:
    - "8080:8080"
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    links:
    - frontend
    - bff
  frontend:
    build:
      context: "frontend/web"
      dockerfile: "Dockerfile"
      # target: develop
    image: oyas/web-app-frontend:${IMAGE_TAG}
    ports:
    - "8000:8000"
    # volumes:
    # - ./frontend/web:/app
    links:
    - bff
    environment:
    - API_URL_BFF=http://bff:4000
    - API_URL_BFF_RUNTIME=  # same host
  bff:
    build:
      context: backend
      dockerfile: "Dockerfile.node"
    image: oyas/web-app-bff:${IMAGE_TAG}
    ports:
    - "4000:4000"
    links:
    - greeter_server
    - articles
    environment:
    - API_URL_ARTICLES=articles:50052
  greeter_server:
    build:
      context: backend
      dockerfile: "Dockerfile.go"
      target: app
      args:
        SERVICE_NAME: "greeter_server"
    ports:
    - "50051:50051"
    links:
    - redis
  articles:
    build:
      context: backend
      dockerfile: "Dockerfile.go"
      target: app
      args:
        SERVICE_NAME: "articles"
    image: oyas/web-app-articles:${IMAGE_TAG}
    ports:
    - "50052:50052"
    links:
    - redis-articles
  redis:
    image: "redis:alpine"
  redis-articles:
    image: "redis:alpine"
