version: '3.7'
services:
  nginx:
    image: "nginx:alpine"
    ports:
    - "9000:8080"
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    links:
    - frontend
    - bff
  frontend:
    build:
      context: "frontend/web"
      dockerfile: "Dockerfile"
      # target: develop
    image: oyas/web-app-frontend:${IMAGE_TAG}
    ports:
    - "8000:8000"
    # volumes:
    # - ./frontend/web:/app
    links:
    - bff
    environment:
    - API_URL_BFF=http://bff:4000
    - API_URL_BFF_RUNTIME=  # same host
  bff:
    build:
      context: backend
      dockerfile: "Dockerfile.node"
    image: oyas/web-app-bff:${IMAGE_TAG}
    ports:
    - "4000:4000"
    links:
    - greeter_server
    - articles
    environment:
    - API_URL_ARTICLES=articles:50052
    - APP_JAEGER_URL=http://jaeger:14268
  greeter_server:
    build:
      context: backend
      dockerfile: "Dockerfile.go"
      target: app
      args:
        SERVICE_NAME: "greeter_server"
    ports:
    - "50051:50051"
    links:
    - redis
  articles:
    build:
      context: backend
      dockerfile: "Dockerfile.go"
      target: app
      args:
        SERVICE_NAME: "articles"
    image: oyas/web-app-articles:${IMAGE_TAG}
    ports:
    - "50052:50052"
    links:
    - redis-articles
    - jaeger
    environment:
    - APP_REDIS_URL=redis-articles:6379
    - APP_JAEGER_URL=http://jaeger:14268
    # - JAEGER_AGENT_PORT=6831
  redis:
    image: "redis:alpine"
  redis-articles:
    image: "redis:alpine"
  jaeger:
    image: jaegertracing/all-in-one:1.22
    ports:
    - "5775:5775"
    - "6831:6831/udp"
    - "6832:6832"
    - "5778:5778"
    - "16686:16686"
    - "14268:14268"
    - "14250:14250"
