#
# Usage
#   $ docker-compose -f test.yaml build
#
version: '3.7'
services:
  articles:
    build:
      context: backend
      dockerfile: "Dockerfile.go"
      target: test
      args:
        SERVICE_NAME: "articles"
