version: '3'
services:
  bff:
    build:
      context: .
      dockerfile: "Dockerfile.node"
    ports:
    - "4000:4000"
    links:
    - greeter_server
  greeter_server:
    build:
      context: .
      dockerfile: "Dockerfile.go"
      args:
        SERVICE_NAME: "greeter_server"
    ports:
    - "50051:50051"
    links:
    - redis
  redis:
    image: "redis:alpine"
