# FROM gcr.io/distroless/nodejs:14
FROM node:14-alpine

RUN mkdir -p /app/bff

WORKDIR /app/bff

COPY bff/package*.json ./

RUN npm install
# 本番用にコードを作成している場合
# RUN npm install --only=production

COPY ./protos /app/protos
COPY ./bff /app/bff

RUN npm run generate

EXPOSE 4000
CMD [ "npm", "start" ]
