name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
      -
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: Build services
        env:
          IMAGE_TAG: ${{ github.sha }}
          CACHE_SRC_DIR: /tmp/.buildx-cache
          CACHE_DIST_DIR: /tmp/.buildx-cache-new
        uses: docker/bake-action@master
        with:
          files: docker-bake.hcl
      -
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  test:
    runs-on: ubuntu-latest

    steps:
      -
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ignored-${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: Generate RSA keys
        run: bash backend/auth/keys/generate.sh
      -
        name: Test services
        env:
          CACHE_SRC_DIR: /tmp/.buildx-cache
        uses: docker/bake-action@master
        with:
          files: docker-bake.hcl
          targets: test

  test2:
    runs-on: ubuntu-latest

    steps:
      -
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ignored-${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: Generate RSA keys
        run: bash backend/auth/keys/generate.sh
      -
        name: Build services
        env:
          IMAGE_TAG: ${{ github.sha }}
          CACHE_SRC_DIR: /tmp/.buildx-cache
          CACHE_DIST_DIR: /tmp/.buildx-cache-new
        uses: docker/bake-action@master
        with:
          files: docker-bake.hcl
          load: true
      -
        name: Show images
        run: |
          docker images
      -
        name: Start services
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker-compose up -d
          sleep 10
      -
        name: Show images
        run: |
          docker images
      -
        name: Check status of services
        run: |
          docker-compose logs
          echo ""
          docker-compose ps
          echo ""
          ps=`docker-compose ps | sed '1,2d'`
          all_count=`echo "$ps" | wc -l`
          up_count=`echo "$ps" | grep '   Up' | wc -l`
          if [[ $all_count != $up_count ]]; then
              echo "some services down (${up_count}/${all_count})"
              exit 1
          fi
          echo "All ok"
      -
        name: Get root page
        run: curl -LI localhost:9000 --fail -sS --retry 60 --retry-delay 2
      -
        name: The job has failed
        if: ${{ failure() }}
        run: docker-compose logs
      -
        name: Stop services
        run: docker-compose down
