# This is a basic workflow to help you get started with Actions

name: CI/CD

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment:
      name: production

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build services
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: docker-compose build

      - name: Start services
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker-compose up -d
          sleep 10

      - name: Check status of services
        run: |
          docker-compose logs
          echo ""
          docker-compose ps
          echo ""
          ps=`docker-compose ps | sed '1,2d'`
          all_count=`echo "$ps" | wc -l`
          up_count=`echo "$ps" | grep '   Up' | wc -l`
          if [[ $all_count != $up_count ]]; then
              echo "some services down (${up_count}/${all_count})"
              exit 1
          fi
          echo "All ok"

      - name: Get root page
        run: curl -LI localhost:8080 --fail -sS --retry 300 --retry-delay 2

      - name: Stop services
        run: docker-compose down

      - name: push image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker login -u oyas -p ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          docker-compose push

  # second job
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test services
        run: docker-compose -f test.yaml build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: imranismail/setup-kustomize@v1
      with:
        kustomize-version: "3.9.4"

    - run: git clone https://${REPO_TOKEN}@github.com/oyas/web-app-infra.git
      env:
        REPO_TOKEN: ${{secrets.ACCESS_TOKEN_GITHUB}}

    - run: |
        cd web-app-infra/apps/articles/overlays/dev
        kustomize edit set image oyas/web-app-articles:${GITHUB_SHA}
    
    - run: |
        cd web-app-infra/apps/bff/overlays/dev/
        kustomize edit set image oyas/web-app-bff:${GITHUB_SHA}
    
    - run: |
        cd web-app-infra/apps/frontend/overlays/dev/
        kustomize edit set image oyas/web-app-frontend:${GITHUB_SHA}

    - run: git add .
    - run: git commit -m "[GITHUB action] Set image tag to `${GITHUB_SHA}`"
    - run: git push
